<?php
// $Id$

/**
 * @file
 * This this the main LDAP API module.
 *
 * This module will make the ldap API available to other modules.
 * Designed to provide a light but flexible assortment of functions
 * and constants, with more functionality in additional files that
 * are not loaded unless other modules specifically include them.
 *
 * @see http://datatracker.ietf.org/doc/rfc4510/
 * @see http://datatracker.ietf.org/doc/rfc4511/
 * @see http://datatracker.ietf.org/doc/rfc4512/
 * @see http://datatracker.ietf.org/doc/rfc4513/
 * @see http://datatracker.ietf.org/doc/rfc4514/
 * @see http://datatracker.ietf.org/doc/rfc4515/
 * @see http://datatracker.ietf.org/doc/rfc4516/
 * @see http://datatracker.ietf.org/doc/rfc4517/
 * @see http://datatracker.ietf.org/doc/rfc4518/
 * @see http://datatracker.ietf.org/doc/rfc4519/
 */

/**
 * Implementation of hook_init().
 */

/**
 * Implementation of hook_theme().
 */
function ldap_api_theme() {
  return array(
    'ldap_api_list_servers_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'ldap_servers.theme.inc'
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function ldap_api_perm(){
  return array('Add/Edit LDAP Servers','Delete LDAP Servers','(De-)Activate LDAP Servers');
}

/**
 * Implementation of hook_cron().
 */
function ldap_api_cron() {
}

/**
 * Implementation of hook_menu().
 */
function ldap_api_menu() {
  $items = array();
  $items['admin/settings/ldap'] = array(
    'title' => 'LDAP',
    'page callback' => 'ldap_api_info',
    'access arguments' => array('administer site configuration'),
    'file' => 'ldap_api.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/ldap/info'] = array(
    'title' => 'Info',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/settings/ldap/servers'] = array(
    'title' => 'Servers',
    'description' => 'Configure LDAP Servers',
    'type' => MENU_LOCAL_TASK,
    'file' => 'ldap_servers.admin.inc',
    'page callback' => 'ldap_api_list_servers',
    'access arguments' => array('administer site configuration'),
    'weight' => 1,
  );
  $items['admin/settings/ldap/servers/add'] = array(
    'title' => 'Add',
    'description' => 'Add an LDAP Server',
    'type' => MENU_LOCAL_TASK,
    'file' => 'ldap_servers.admin.inc',
    'page callback' => 'ldap_api_add_server',
    'access arguments' => array('Add/Edit LDAP Servers'),
    'weight' => -1,
  );
  $items['admin/settings/ldap/servers/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $item['admin/settings/ldap/servers/%'] = array (
    'title' => 'Edit',
    'title callback' => 'ldap_api_server_name',
    'title arguments' => array(4),
    'description' => 'Edit an LDAP Server',
    'type' => MENU_CALLBACK,
    'file' => 'ldap_servers.admin.inc',
    'page callback' => 'ldap_api_edit_server',
    'page arguments' => array(4),
    'access arguments' => array('Add/Edit LDAP Servers'),
    'weight' => 0,
  );
  $item['admin/settings/ldap/servers/%/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  return $items;
}

/**
 * Implementation of hook_simpletest().
 */
function ldap_api_simpletest() {
  $dir = drupal_get_path('module', 'ldap_api') .'/tests';
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}


/**
 * Implementation of hook_flush_caches().
 */
function ldap_api_flush_caches() {
  return array();
}

// vim:fenc=utf-8:ft=php:ai:si:ts=2:sw=2:et:
