<?php

/**
 * @file
 */

/**
 * Implements hook_views_data().
 */
function ldap_views_views_data() {
  $data['ldap_query_entity']['table']['group'] = t('LDAP Query');

  $data['ldap_query_entity']['table']['base'] = [
    'field' => 'id',
    'title' => t('LDAP Query'),
    'help' => t('Data from LDAP Server.'),
  ];

  return $data;
}

/**
 * Legacy code below.
 **/

/**
 *
 */
function ldap_views_get_qid(&$view) {
  $current_display = $view->display[$view->current_display];
  return isset($current_display->display_options['query']['options']['qid']) ?
    $current_display->display_options['query']['options']['qid'] :
    $current_display->handler->default_display->display->display_options['query']['options']['qid'];
}

/**
 * Implements hook_views_data().
 */
function ldap_views_views_data_old() {
  $data['ldap']['table']['group'] = t('LDAP Query');

  // Basedn.
  $data['ldap']['basedn'] = [
    'title' => t('LDAP Base DN'),
    'help' => t('The LDAP search base entry'),
    'argument' => [
      'handler' => 'ldap_views_handler_argument',
    ],
  ];
  // filter
  // Generic column.
  $data['ldap']['attribute'] = [
    'title' => t('LDAP Attribute'),
    'help' => t('An attribute in LDAP Server'),
    'argument' => [
      'handler' => 'ldap_views_handler_argument_attribute',
    ],
    'field' => [
      'handler' => 'ldap_views_handler_field_attribute',
    ],
    'sort' => [
      'handler' => 'ldap_views_handler_sort_attribute',
    ],
    'filter' => [
      'handler' => 'ldap_views_handler_filter_attribute',
    ],
  ];
  $data['ldap']['dn'] = [
    'title' => t('DN'),
    'help' => t('Distinguished name'),
    'field' => [
      'handler' => 'ldap_views_handler_field',
    ],
    'sort' => [
      'handler' => 'ldap_views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
  ];
  $data['ldap']['cn'] = [
    'title' => t('CN'),
    'help' => t('Common name'),
    'argument' => [
      'handler' => 'ldap_views_handler_argument',
    ],
    'field' => [
      'handler' => 'ldap_views_handler_field',
    ],
    'sort' => [
      'handler' => 'ldap_views_handler_sort',
    ],
    'filter' => [
      'handler' => 'ldap_views_handler_filter',
    ],
  ];
  $data['ldap']['objectClass'] = [
    'title' => t('Object Class'),
    'help' => t('The LDAP objectClass'),
    'argument' => [
      'handler' => 'ldap_views_handler_argument',
    ],
    'field' => [
      'handler' => 'ldap_views_handler_field',
    ],
    'sort' => [
      'handler' => 'ldap_views_handler_sort',
    ],
    'filter' => [
      'handler' => 'ldap_views_handler_filter',
    ],
  ];

  return $data;
}
